spring:
  application:
    name: articleback
  datasource:
    url: jdbc:postgresql://34.70.121.23:5432/articles
    username: postgres
    password: gapsi-test-db
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      platform: postgresql
      mode: always

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG